export const ATLAS_DIFFICULTY_TIERS = [1, 2, 3, 4, 5] as const;

export type AtlasDifficultyTier = (typeof ATLAS_DIFFICULTY_TIERS)[number];

export type AtlasTarget = {
  id: string;
  name: string;
  country: string;
  difficulty: AtlasDifficultyTier;
  lat: number;
  lng: number;
  story: string;
};

// Original Playstead town and city descriptions, backed only by ordinary geographic facts.
export const ATLAS_TARGETS: readonly AtlasTarget[] = [
  {
    id: 'paris',
    name: 'Paris',
    country: 'France',
    difficulty: 1,
    lat: 48.8566,
    lng: 2.3522,
    story:
      'Paris grew along the Seine and has served as a major European center of art, culture, and government.',
  },
  {
    id: 'london',
    name: 'London',
    country: 'United Kingdom',
    difficulty: 1,
    lat: 51.5074,
    lng: -0.1278,
    story:
      "London developed around a crossing of the River Thames and became one of the world's largest cities.",
  },
  {
    id: 'new-york',
    name: 'New York City',
    country: 'United States',
    difficulty: 1,
    lat: 40.7128,
    lng: -74.006,
    story:
      "New York's natural harbor helped it become a global center shaped by generations of migration.",
  },
  {
    id: 'tokyo',
    name: 'Tokyo',
    country: 'Japan',
    difficulty: 1,
    lat: 35.6762,
    lng: 139.6503,
    story:
      "Tokyo expanded from the castle town of Edo into the center of Japan's largest metropolitan area.",
  },
  {
    id: 'sydney',
    name: 'Sydney',
    country: 'Australia',
    difficulty: 1,
    lat: -33.8688,
    lng: 151.2093,
    story: "Sydney surrounds a branching natural harbor on Australia's Pacific coast.",
  },
  {
    id: 'rome',
    name: 'Rome',
    country: 'Italy',
    difficulty: 1,
    lat: 41.9028,
    lng: 12.4964,
    story:
      'Rome spans the Tiber River and preserves layers of history from the ancient city onward.',
  },
  {
    id: 'cairo',
    name: 'Cairo',
    country: 'Egypt',
    difficulty: 1,
    lat: 30.0444,
    lng: 31.2357,
    story: 'Cairo lies beside the Nile near the point where its valley opens into the delta.',
  },
  {
    id: 'rio',
    name: 'Rio de Janeiro',
    country: 'Brazil',
    difficulty: 1,
    lat: -22.9068,
    lng: -43.1729,
    story:
      'Rio wraps around bays and mountains, with neighborhoods climbing between tropical forest and ocean.',
  },
  {
    id: 'lisbon',
    name: 'Lisbon',
    country: 'Portugal',
    difficulty: 2,
    lat: 38.7223,
    lng: -9.1393,
    story: 'Lisbon rises over the Tagus estuary, with steep streets long served by yellow trams.',
  },
  {
    id: 'reykjavik',
    name: 'Reykjavík',
    country: 'Iceland',
    difficulty: 2,
    lat: 64.1466,
    lng: -21.9426,
    story:
      'Reykjavík grew from a small settlement into a capital heated largely by geothermal energy.',
  },
  {
    id: 'istanbul',
    name: 'Istanbul',
    country: 'Türkiye',
    difficulty: 2,
    lat: 41.0082,
    lng: 28.9784,
    story:
      'Istanbul has connected seas, continents, and empires from its position around the Bosporus.',
  },
  {
    id: 'cape-town',
    name: 'Cape Town',
    country: 'South Africa',
    difficulty: 2,
    lat: -33.9249,
    lng: 18.4241,
    story:
      'Cape Town occupies a peninsula between Table Bay, steep mountains, and the Atlantic Ocean.',
  },
  {
    id: 'singapore',
    name: 'Singapore',
    country: 'Singapore',
    difficulty: 2,
    lat: 1.3521,
    lng: 103.8198,
    story:
      'Singapore sits near the southern tip of the Malay Peninsula where major maritime routes converge.',
  },
  {
    id: 'kyoto',
    name: 'Kyoto',
    country: 'Japan',
    difficulty: 2,
    lat: 35.0116,
    lng: 135.7681,
    story:
      'Kyoto preserves gardens, shrines, workshops, and districts shaped by more than a millennium of history.',
  },
  {
    id: 'vancouver',
    name: 'Vancouver',
    country: 'Canada',
    difficulty: 2,
    lat: 49.2827,
    lng: -123.1207,
    story:
      'Vancouver sits between the Strait of Georgia and the Coast Mountains in western Canada.',
  },
  {
    id: 'buenos-aires',
    name: 'Buenos Aires',
    country: 'Argentina',
    difficulty: 2,
    lat: -34.6037,
    lng: -58.3816,
    story: 'Buenos Aires spreads across the western shore of the broad Río de la Plata estuary.',
  },
  {
    id: 'marrakesh',
    name: 'Marrakesh',
    country: 'Morocco',
    difficulty: 3,
    lat: 31.6295,
    lng: -7.9811,
    story:
      "Marrakesh grew around a lively medina, gardens, and trading routes near Morocco's mountain foothills.",
  },
  {
    id: 'cusco',
    name: 'Cusco',
    country: 'Peru',
    difficulty: 3,
    lat: -13.5319,
    lng: -71.9675,
    story: 'Cusco occupies a high Andean valley and was the political heart of the Inca Empire.',
  },
  {
    id: 'ljubljana',
    name: 'Ljubljana',
    country: 'Slovenia',
    difficulty: 3,
    lat: 46.0569,
    lng: 14.5058,
    story: 'Ljubljana follows a bend of the Ljubljanica River beneath a castle-topped hill.',
  },
  {
    id: 'chiang-mai',
    name: 'Chiang Mai',
    country: 'Thailand',
    difficulty: 3,
    lat: 18.7883,
    lng: 98.9853,
    story:
      'Chiang Mai began as a walled northern capital in a basin surrounded by forested mountains.',
  },
  {
    id: 'cartagena',
    name: 'Cartagena',
    country: 'Colombia',
    difficulty: 3,
    lat: 10.391,
    lng: -75.4794,
    story:
      'Cartagena grew around a sheltered Caribbean harbor and a fortified colonial-era center.',
  },
  {
    id: 'tbilisi',
    name: 'Tbilisi',
    country: 'Georgia',
    difficulty: 3,
    lat: 41.7151,
    lng: 44.8271,
    story:
      'Tbilisi stretches through the narrow Mtkvari River valley between hills in the South Caucasus.',
  },
  {
    id: 'porto',
    name: 'Porto',
    country: 'Portugal',
    difficulty: 3,
    lat: 41.1579,
    lng: -8.6291,
    story: 'Porto climbs the steep northern bank of the Douro near its Atlantic mouth.',
  },
  {
    id: 'hanoi',
    name: 'Hanoi',
    country: 'Vietnam',
    difficulty: 3,
    lat: 21.0278,
    lng: 105.8342,
    story: 'Hanoi developed among lakes and rivers on the low plains of the Red River delta.',
  },
  {
    id: 'timbuktu',
    name: 'Timbuktu',
    country: 'Mali',
    difficulty: 4,
    lat: 16.7666,
    lng: -3.0026,
    story:
      'Timbuktu flourished beside Niger River trade routes as a celebrated center of scholarship.',
  },
  {
    id: 'lalibela',
    name: 'Lalibela',
    country: 'Ethiopia',
    difficulty: 4,
    lat: 12.0317,
    lng: 39.0476,
    story: 'Lalibela is a highland town known for medieval churches excavated from volcanic rock.',
  },
  {
    id: 'ulaanbaatar',
    name: 'Ulaanbaatar',
    country: 'Mongolia',
    difficulty: 4,
    lat: 47.8864,
    lng: 106.9057,
    story: 'Ulaanbaatar fills a high valley along the Tuul River between four sacred mountains.',
  },
  {
    id: 'valparaiso',
    name: 'Valparaíso',
    country: 'Chile',
    difficulty: 4,
    lat: -33.0472,
    lng: -71.6127,
    story: 'Valparaíso rises in a natural amphitheater of steep hills around a Pacific port.',
  },
  {
    id: 'luang-prabang',
    name: 'Luang Prabang',
    country: 'Laos',
    difficulty: 4,
    lat: 19.8833,
    lng: 102.1333,
    story: 'Luang Prabang occupies a narrow peninsula where the Nam Khan meets the Mekong.',
  },
  {
    id: 'sarajevo',
    name: 'Sarajevo',
    country: 'Bosnia and Herzegovina',
    difficulty: 4,
    lat: 43.8563,
    lng: 18.4131,
    story: 'Sarajevo extends along the Miljacka River in a mountain basin of the Dinaric Alps.',
  },
  {
    id: 'antananarivo',
    name: 'Antananarivo',
    country: 'Madagascar',
    difficulty: 4,
    lat: -18.8792,
    lng: 47.5079,
    story:
      "Antananarivo spreads across a series of steep ridges in Madagascar's central highlands.",
  },
  {
    id: 'samarkand',
    name: 'Samarkand',
    country: 'Uzbekistan',
    difficulty: 4,
    lat: 39.6542,
    lng: 66.9597,
    story: 'Samarkand prospered at a crossroads of trade routes through Central Asia.',
  },
  {
    id: 'ngerulmud',
    name: 'Ngerulmud',
    country: 'Palau',
    difficulty: 5,
    lat: 7.5004,
    lng: 134.6243,
    story: "Ngerulmud is Palau's small capital settlement on the island of Babeldaob.",
  },
  {
    id: 'gjirokaster',
    name: 'Gjirokastër',
    country: 'Albania',
    difficulty: 5,
    lat: 40.0758,
    lng: 20.1389,
    story: 'Gjirokastër climbs a steep hillside above the Drino valley in southern Albania.',
  },
  {
    id: 'lamu',
    name: 'Lamu',
    country: 'Kenya',
    difficulty: 5,
    lat: -2.2717,
    lng: 40.902,
    story: "Lamu is a historic Swahili town on a low island just off Kenya's Indian Ocean coast.",
  },
  {
    id: 'kpalime',
    name: 'Kpalimé',
    country: 'Togo',
    difficulty: 5,
    lat: 6.9,
    lng: 0.6333,
    story: "Kpalimé lies near the forested Togo Mountains in the country's southwest.",
  },
  {
    id: 'dolisie',
    name: 'Dolisie',
    country: 'Republic of the Congo',
    difficulty: 5,
    lat: -4.1997,
    lng: 12.6739,
    story: 'Dolisie sits among wooded hills on an important rail corridor in southwestern Congo.',
  },
  {
    id: 'tsetserleg',
    name: 'Tsetserleg',
    country: 'Mongolia',
    difficulty: 5,
    lat: 47.4769,
    lng: 101.4503,
    story:
      'Tsetserleg occupies a sheltered valley beside the Khangai Mountains in central Mongolia.',
  },
  {
    id: 'san-ignacio',
    name: 'San Ignacio',
    country: 'Belize',
    difficulty: 5,
    lat: 17.1523,
    lng: -89.08,
    story: 'San Ignacio stands beside the Macal River in the forested hills of western Belize.',
  },
  {
    id: 'banska-stiavnica',
    name: 'Banská Štiavnica',
    country: 'Slovakia',
    difficulty: 5,
    lat: 48.4585,
    lng: 18.8966,
    story:
      'Banská Štiavnica fills the center of an ancient volcanic caldera shaped by centuries of mining.',
  },
] as const;
